StringLiterals:
  EnforcedStyle: single_quotes

Style/InlineComment:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/LineLength:
  Max: 120
  AllowURI: true

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false