StringLiterals:
  EnforcedStyle: single_quotes

Style/InlineComment:
  Enabled: true

MethodCalledOnDoEndBlock:
  Enabled: true

HashSyntax:
  Enabled: false

LineLength:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

SymbolArray:
  Enabled: true

TrailingBlankLines:
  Enabled: false

TrailingWhitespace:
  Enabled: false