matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.1.8.7
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.1.1
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: ree
      gemfile: gemfiles/Gemfile.1.8.7
    - rvm: jruby
      gemfile: gemfiles/Gemfile.1.9.2+
  allow_failures:
    - rvm: 1.8.7
    - rvm: ree